version: "3"
services:
  database:
    restart: always
    ports:
     - 5432:5432
    image: postgres:10.3
    volumes:
     - ./data:/var/lib/postgresql/data
    env_file:
      - .env
  service:
    restart: always
    image: s6igitlab.gel.usherbrooke.ca:4567/degel/degel-backend:latest
    ports:
      - 8080:8080
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8080
    entrypoint:
      - java
      - -Djava.security.egd=file:/dev/./urandom
      - -jar
      - -Dspring.profiles.active=deploy
      - app.jar
    depends_on:
      - database
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro