version: "3"
services:
  database:
    restart: always
    ports:
     - 5432:5432
    image: postgres:10.3
    volumes:
     - ./data:/var/lib/postgresql/data
    env_file:
      - .env
  service:
    restart: always
    build: ./
    ports:
      - 8080:8080
    depends_on:
      - database