spring:
  profiles:
    active: local

  jpa:
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway.enabled: true

  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

app:
  security:
    cas-server: https://cas.usherbrooke.ca
    access-token-validity: 7200
    refresh-token-validity: 10368000