spring:
  profiles:
    active: local

  jpa:
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway.enabled: true

  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

  feign:
    okhttp:
      enabled: true

logging:
  level:
    org.springframework.context.support.ResourceBundleMessageSource: ERROR
    org.springframework.security.oauth2.provider.token.store.JdbcTokenStore: WARN

app:
  security:
    cas-server: https://cas.usherbrooke.ca
  calendar:
    horarius: https://www.gel.usherbrooke.ca/horarius
    refresh-delay: 300000 # 5min
  notification:
    expo-server: https://exp.host/--/api/v2/push/send
    notifyus:
      server: http://s6iprojet01.gel.usherbrooke.ca
